language: python

os:
 - linux
 - osx

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

install:
 - pip install .
 - pip install pytest pytest-cov mock

script: make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
